  spring:
    application:
      name: bounce
    datasource:
      url: jdbc:mysql://localhost:3306/vending_machine
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver

  server:
    port: 9001

  management:
    endpoints:
      web:
        exposure:
          include: "*"  # Enable all actuator endpoints
        base-path: /actuator  # Base path for actuator endpoints

  camel:
    springboot:
      auto-startup: true
      route-controller-supervise-enabled: true

  email:
    enabled: true
    host: "smtp.gmail.com"
    port: 25
    development-team-email: "developer@gmail.com"
    database-team-email: "database.team@gmail.com"


  monitoring:
    start-time: "07:00"
    end-time: "23:55"
    allowed-days:
      - MONDAY
      - TUESDAY
      - WEDNESDAY
      - THURSDAY
      - FRIDAY
      - SUNDAY
    system:
        enabled: false
        cpu-usage-threshold: 90
        memory-usage-threshold: 90
        disk-usage-threshold: 90
        timer-period: 60000

    database:
      enabled: true
      timer-period: 60000
      health-check-query: "SELECT 1"

    process:
      enabled: false
      timer-period: 60000
      items:
        - name: "java"
          install-path: "C:/Program Files/Java/jdk/bin/java.exe"
          start-command: "java -jar app.jar"

        - name: "notepad.exe"
          install-path: "C:/Windows/System32/notepad.exe"
          start-command: "notepad"

    scheduler:
      enabled: true
      jobs-path: "C:/Projects/Java/bounce/src/main/resources/jobs"
      jobs:
        - name: "clean logs"
          enabled: false
          cron-expression: "0 33 15 ? * MON-FRI *"
          script: "clean_files_recursive.sh"
          arguments: "/var/logs 5 \"*.log\" \"*.dat\""

        - name: "reset tokens"
          enabled: false
          cron-expression: "0 30 6 ? * MON-FRI *"
          script: "call_api.sh"
          args: "\"https://reset-tokens?cache=true\""

        - name: "call api test"
          enabled: true
          cron-expression: "0 27 16 ? * MON-FRI *"
          script: "call_api.bat"
          args: "\"https://jsonplaceholder.typicode.com/posts/1\"  GET"














