  spring:
    application:
      name: bounce
    datasource:
      url: jdbc:mysql://localhost:3306/vending_machine
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver

  server:
    port: 9001

  management:
    endpoints:
      web:
        exposure:
          include: "*"  # Enable all actuator endpoints
        base-path: /actuator  # Base path for actuator endpoints

  camel:
    springboot:
      auto-startup: true
      route-controller-supervise-enabled: true

  email:
    enabled: true
    host: "smtp.gmail.com"
    port: 25
    development-team-email: "developer@gmail.com"
    database-team-email: "database.team@gmail.com"


  monitoring:
    start-time: "01:00"
    end-time: "06:55"
    allowed-days:
      - MONDAY
      - TUESDAY
      - WEDNESDAY
      - THURSDAY
      - FRIDAY
      - SUNDAY
    system:
        enabled: true
        timer-period: 60000
    database:
      enabled: true
      timer-period: 60000
      health-check-query: "SELECT 1"

    process:
      enabled: false
      timer-period: 60000
      items:
        - name: "java"
          install-path: "C:/Program Files/Java/jdk/bin/java.exe"
          start-command: "java -jar app.jar"
        - name: "notepad.exe"
          install-path: "C:/Windows/System32/notepad.exe"
          start-command: "notepad"
    rest:
      enabled: true
      timer-period: 60000
      items:
        - name: "Google"
          url: "http://www.google.com"
          method: "GET"
          expected-status-code: 200
          expected-response: "OK"
          headers:
            Authorization: "Bearer 1234567890"
        - name: "Actuator"
          url: "http://localhost:9001/actuator/health"
          method: "GET"
          expected-status-code: 200
          expected-response: "UP"
          headers:












